<?php
/**
 * @file
 * This module allow the user to consume an API of employees
 *
 */
require_once dirname(__FILE__) . DIRECTORY_SEPARATOR . 'michael_page.inc';

/**
* Implements of hook_menu()
**/
function michael_page_menu(){
   $items['admin/config/system/michael_page'] = array(
    'title' => t('Michael Page'),
    'description' => 'View events that have recently been logged.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('access content'),
    'page arguments' => array('michael_page_form'),
    'type' => MENU_NORMAL_ITEM
  );
  return $items;
}

/**
* Implements of hook_form()
**/
function michael_page_form($form, &$form_state) {
  $form['settings'] = array(
    '#type' => 'vertical_tabs',
  );
  $form['api_settings'] = array(
    '#type' => 'fieldset',
    '#title' => t('Api configuration'),
    '#collapsible' => true,
    '#collapsed' => false,
    '#group' => 'settings',
  );
  $form['api_settings']['api_endpoint'] = array(
    '#type' => 'textfield',
    '#title' => t('api_endpoint'),
    '#default_value' => variable_get('api_endpoint', 'http://dummy.restapiexample.com/api/'),
    '#size' => 60,
    '#maxlength' => 60,
    '#required' => TRUE,
    '#description' => 'Write api_endpoint',
  );
  $form['api_settings']['api_version'] = array(
    '#type' => 'textfield',
    '#title' => t('api_version'),
    '#default_value' => variable_get('api_version', 'v1'),
    '#size' => 60,
    '#maxlength' => 60,
    '#required' => TRUE,
    '#description' => 'Write api_endpoint',
  );
  $form['api_settings']['method_route'] = array(
    '#type' => 'textfield',
    '#title' => t('method_route'),
    '#default_value' => variable_get('method_route', 'employees'),
    '#size' => 60,
    '#maxlength' => 60,
    '#required' => TRUE,
    '#description' => 'Route of the employee route',
  );
  $form['api_settings']['preview'] = array(
    '#type' =>'submit', 
    '#value' => t('Import'), 
    '#submit' => array('import_employees'),
    '#weight' => 19,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
  return $form;
}

/**
* Implements of hook_form_submit()
**/
function michael_page_form_submit($form, &$form_state){
  variable_set('api_endpoint',$form_state['values']['api_endpoint']);
  variable_set('api_version',$form_state['values']['api_version']);
  variable_set('method_route',$form_state['values']['method_route']);
}


/**
* Implements of hook_views_api()
**/
Function michael_page_views_api(){
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module','michael_page'),
  );
}

/**
* Implements hook_views_default_views().
**/
function michael_page_views_default_views() {
  $files = file_scan_directory(drupal_get_path('module','michael_page').'/views','/.view/');
  foreach($files as $filepath => $file) {
    require $filepath;
    if(isset($view)) {
      $views[$view->name] = $view;
    }
  }
  if($views) {
    return $views;
  }
}